
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-01
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxNDk3ODM2","is_bot":false,"login":"oscar-luna","name":"Oscar Luna"},"headRefName":"classrooms_api","number":24,"title":"Creates API endpoint to get classrooms for a building","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/24"},{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"courses_ran","number":23,"title":"Create a serach page under other searches","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/23"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"as-GESearchPage-placeholder","number":22,"title":"as - add placeholder for GESearchPage","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/22"}]
