
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-01
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-01
pull_requests: [{"author":{"id":"U_kgDOBtQNyQ","is_bot":false,"login":"rankesterc","name":"Ran Chen"},"headRefName":"rc_backend_ge_controller","number":34,"title":"Added the backend controller that returns search result for general education search","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/34"},{"author":{"id":"U_kgDOB3Dlbw","is_bot":false,"login":"hjin133","name":""},"headRefName":"hjin133-paginate-frontend","number":33,"title":"hj - paginate frontend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/33"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"as-SectionsTable-Refactor","number":32,"title":"as - added tests to remove large stryker exception","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/32"},{"author":{"id":"U_kgDOCeRySA","is_bot":false,"login":"llexuan","name":""},"headRefName":"proj-dropdown-for-classrooms","number":30,"title":"add classroom dropdown","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/30"},{"author":{"id":"U_kgDOCML-SQ","is_bot":false,"login":"alecsekimoto1","name":""},"headRefName":"as-GESearchForm","number":29,"title":"as - GeneralEducationSearchForm and Tests","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/29"},{"author":{"id":"MDQ6VXNlcjkxNDk3ODM2","is_bot":false,"login":"oscar-luna","name":"Oscar Luna"},"headRefName":"classrooms_frontend","number":26,"title":"Imports availableClassrooms into frontend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-01/pull/26"}]
