
name: "00-publish-docs-to-github-pages-setup: set up -docs and -docs-qa repos (run once, manually)"
on: 
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Create -docs repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          DESC="Documentation for ${OWNER_PLUS_REPOSITORY}"
          OWNER=${{ github.repository_owner }}
          TEMPLATE="https://github.com/${OWNER}/TEMPLATE-docs"
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}      
          echo "Trying to create https://github.com/${NEW_REPO} if it doesn't already exist"
          gh repo create ${NEW_REPO} --public --description "${DESC}" --template ${TEMPLATE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Set homepage in -docs repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}
          echo "Trying to set HOMEPAGE=${HOMEPAGE} on NEW_REPO=${NEW_REPO}"
          gh repo edit ${NEW_REPO} --homepage ${HOMEPAGE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Create -docs-qa repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs-qa"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          DESC="Documentation for ${OWNER_PLUS_REPOSITORY}"
          OWNER=${{ github.repository_owner }}
          TEMPLATE="https://github.com/${OWNER}/TEMPLATE-docs"
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}      
          echo "Trying to create https://github.com/${NEW_REPO} if it doesn't already exist"
          gh repo create ${NEW_REPO} --public --description "${DESC}" --template ${TEMPLATE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Set homepage in -docs-qa repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs-qa"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}
          echo "Trying to set HOMEPAGE=${HOMEPAGE} on NEW_REPO=${NEW_REPO}"
          gh repo edit ${NEW_REPO} --homepage ${HOMEPAGE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
